export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_FULFILLED = 'GET_CATEGORIES_FULFILLED';

export const GET_NEARBY_PLACES = 'GET_NEARBY_PLACES';
export const GET_NEARBY_PLACES_FULFILLED = 'GET_NEARBY_PLACES_FULFILLED';
