export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_FULFILLED = 'GET_CATEGORIES_FULFILLED';

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_FULFILLED = 'GET_CATEGORY_FULFILLED';